
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Oct 20 12:43:19 CST 2022
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Comma = 44;
  public static final int Or = 30;
  public static final int Class = 2;
  public static final int True = 13;
  public static final int Digit = 47;
  public static final int Exclam = 43;
  public static final int RightKey = 37;
  public static final int SemiColom = 31;
  public static final int LeftKey = 36;
  public static final int If = 7;
  public static final int DecimalLiteral = 52;
  public static final int Id = 49;
  public static final int BracketOpenClose = 39;
  public static final int ParentOpenClose = 38;
  public static final int Void = 4;
  public static final int GreaterThan = 24;
  public static final int Equal = 27;
  public static final int LeftBracket = 34;
  public static final int Else = 8;
  public static final int Break = 11;
  public static final int StringLiteral = 41;
  public static final int AsignAdd = 16;
  public static final int RightBracket = 35;
  public static final int AsignSubs = 17;
  public static final int Return = 10;
  public static final int NotEqual = 28;
  public static final int Substract = 19;
  public static final int Division = 21;
  public static final int Int = 5;
  public static final int LessEqualThan = 25;
  public static final int HexLiteral = 51;
  public static final int For = 9;
  public static final int EOF = 0;
  public static final int Asign = 15;
  public static final int And = 29;
  public static final int error = 1;
  public static final int GreaterEqualThan = 26;
  public static final int False = 14;
  public static final int Alpha = 48;
  public static final int ERROR = 45;
  public static final int KeyOpenClose = 40;
  public static final int RightParent = 33;
  public static final int Continue = 12;
  public static final int LessThan = 23;
  public static final int String = 46;
  public static final int Callout = 42;
  public static final int Add = 18;
  public static final int LeftParent = 32;
  public static final int Mod = 22;
  public static final int Multiplication = 20;
  public static final int HexDigit = 50;
  public static final int Boolean = 6;
  public static final int Program = 3;
}

