
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 03 23:12:01 CST 2022
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Comma = 51;
  public static final int Or = 37;
  public static final int Class = 2;
  public static final int True = 13;
  public static final int Exclam = 50;
  public static final int RightKey = 44;
  public static final int SemiColom = 38;
  public static final int Digit = 16;
  public static final int LeftKey = 43;
  public static final int If = 7;
  public static final int DecimalLiteral = 21;
  public static final int BracketOpenClose = 46;
  public static final int ParentOpenClose = 45;
  public static final int Id = 18;
  public static final int Void = 4;
  public static final int GreaterThan = 31;
  public static final int Equal = 34;
  public static final int LeftBracket = 41;
  public static final int Else = 8;
  public static final int Break = 11;
  public static final int StringLiteral = 48;
  public static final int AsignAdd = 23;
  public static final int RightBracket = 42;
  public static final int AsignSubs = 24;
  public static final int Return = 10;
  public static final int NotEqual = 35;
  public static final int Substract = 26;
  public static final int Division = 28;
  public static final int Int = 5;
  public static final int LessEqualThan = 32;
  public static final int HexLiteral = 20;
  public static final int For = 9;
  public static final int EOF = 0;
  public static final int Asign = 22;
  public static final int And = 36;
  public static final int error = 1;
  public static final int GreaterEqualThan = 33;
  public static final int False = 14;
  public static final int Alpha = 17;
  public static final int ERROR = 52;
  public static final int KeyOpenClose = 47;
  public static final int RightParent = 40;
  public static final int Continue = 12;
  public static final int LessThan = 30;
  public static final int String = 15;
  public static final int Callout = 49;
  public static final int Add = 25;
  public static final int LeftParent = 39;
  public static final int Mod = 29;
  public static final int Multiplication = 27;
  public static final int Boolean = 6;
  public static final int HexDigit = 19;
  public static final int Program = 3;
}

