
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package tarea2;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int menor_que = 4;
  public static final int diferenciacion = 3;
  public static final int decimal = 27;
  public static final int not = 13;
  public static final int nor = 9;
  public static final int numero = 26;
  public static final int nand = 11;
  public static final int mayor_o_igual = 7;
  public static final int or = 8;
  public static final int false_ = 21;
  public static final int multiplicacion = 16;
  public static final int Ipar = 20;
  public static final int resta = 15;
  public static final int tchar = 29;
  public static final int menor_o_igual = 5;
  public static final int igualacion = 2;
  public static final int tstring = 28;
  public static final int EOF = 0;
  public static final int verdadero = 24;
  public static final int division = 17;
  public static final int true_ = 23;
  public static final int potencia = 18;
  public static final int Dpar = 19;
  public static final int error = 1;
  public static final int xor = 12;
  public static final int null_ = 25;
  public static final int mayor_que = 6;
  public static final int suma = 14;
  public static final int falso = 22;
  public static final int and = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "igualacion",
  "diferenciacion",
  "menor_que",
  "menor_o_igual",
  "mayor_que",
  "mayor_o_igual",
  "or",
  "nor",
  "and",
  "nand",
  "xor",
  "not",
  "suma",
  "resta",
  "multiplicacion",
  "division",
  "potencia",
  "Dpar",
  "Ipar",
  "false_",
  "falso",
  "true_",
  "verdadero",
  "null_",
  "numero",
  "decimal",
  "tstring",
  "tchar"
  };
}

